{"name": "test_assume", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_demo_case.py:10: AssumptionFailure\n>>\tassume(a > b)\nAssertionError:", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_demo_case.py:10: AssumptionFailure\nE               >>\tassume(a > b)\nE               AssertionError:\n\nC:\\Users\\段海洋\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\six.py:718: FailedAssumption"}, "attachments": [{"name": "log", "source": "18cd487e-53f7-4152-811b-cc0321d184dc-attachment.txt", "type": "text/plain"}], "start": 1679483111073, "stop": 1679483111274, "uuid": "1ba8a80c-e75d-4f4a-8da4-bae4e36bbc55", "historyId": "7f44080ab51f1f675e8b954a8c991ee2", "testCaseId": "3935ecba7ab9cd11825d5a668c644f54", "fullName": "test_case.test_demo_case#test_assume", "labels": [{"name": "tag", "value": "assume1"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_demo_case"}, {"name": "host", "value": "sea"}, {"name": "thread", "value": "9864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_demo_case"}]}